# Build Stage
FROM golang:1.20.5 AS build

WORKDIR /usr/src/app

# Copy only the necessary files to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the Go binary with optimizations
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

# Final Stage
FROM alpine:latest

# Copy the Go binary from the build stage
COPY --from=build /usr/src/app/app /app

# Set the working directory
WORKDIR /

# Run the Go binary
CMD ["/app"]