# Build Stage
FROM golang:1.20.5 AS build

WORKDIR /go/src/app

# Copy only the necessary files to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the Go binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/app ./cmd

# Final Stage
FROM alpine:latest

# Copy the Go binary from the build stage
COPY --from=build /go/src/app/ /app

# Ensure executable permission for the binary
RUN chmod +x /app

# Run the Go binary
CMD ["/app"]